# Generated by Django 5.0.1 on 2024-01-30 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectorData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=50)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SectorDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sector_symbol', models.CharField(max_length=100)),
                ('sector_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=50)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StockDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=100)),
                ('company_name', models.TextField()),
                ('email', models.TextField()),
                ('listing_date', models.DateField()),
                ('regulatory_body', models.DateField()),
                ('total_listed_shares', models.FloatField()),
                ('face_value', models.FloatField()),
                ('address', models.TextField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='StockSignal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stochrsi', models.CharField(max_length=10)),
                ('sma', models.CharField(max_length=10)),
                ('rsi', models.CharField(max_length=10)),
                ('momentum', models.CharField(max_length=10)),
                ('macd', models.CharField(max_length=10)),
                ('ema', models.CharField(max_length=10)),
                ('boolinger', models.CharField(max_length=10)),
                ('updated_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TestDatabase',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='sectordetail',
            constraint=models.UniqueConstraint(fields=('id', 'sector_symbol'), name='Uniqe Sector Detail'),
        ),
        migrations.AddField(
            model_name='sectordata',
            name='sector_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sectordetail'),
        ),
        migrations.AddField(
            model_name='stockdetail',
            name='sector_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sectordetail'),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='stock_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.stockdetail'),
        ),
        migrations.AddConstraint(
            model_name='stocksignal',
            constraint=models.UniqueConstraint(fields=('id', 'stochrsi', 'sma', 'rsi', 'momentum', 'macd', 'ema', 'boolinger', 'updated_date'), name='Unique stock signals'),
        ),
        migrations.AddConstraint(
            model_name='sectordata',
            constraint=models.UniqueConstraint(fields=('id', 'ticker', 'date'), name='Unique Sector data'),
        ),
        migrations.AddConstraint(
            model_name='stockdetail',
            constraint=models.UniqueConstraint(fields=('id', 'ticker'), name='Unique Stock detail'),
        ),
        migrations.AddConstraint(
            model_name='stockdata',
            constraint=models.UniqueConstraint(fields=('id', 'ticker', 'date'), name='Unique Stock data'),
        ),
    ]
