# Generated by Django 5.0.1 on 2024-01-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stocksignal',
            name='Unique stock signals',
        ),
        migrations.AddField(
            model_name='stocksignal',
            name='ticker',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='stocksignal',
            constraint=models.UniqueConstraint(fields=('id', 'ticker', 'stochrsi', 'sma', 'rsi', 'momentum', 'macd', 'ema', 'boolinger', 'updated_date'), name='Unique stock signals'),
        ),
    ]
