# Generated by Django 5.0.1 on 2024-01-30 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_stocksignal_unique_stock_signals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksignal',
            name='sector_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sectordetail'),
        ),
    ]
